### ISSUE TITLE
Setting virtualHost automatically

### ISSUE THREAD

**Issue by rnitame** [rnitame/birgrantfile#3]
#2

```
folders:
  - map: ~/applicationPath
    to: /home/vagrant/applicationPath
sites:
  - map: gardening.app
    to: "/home/vagrant/applicationPath/public"
```
